### PR TITLE
Added initial empty project

### PR DESCRIPTION
**Pull request by job13er**
This #patch# delivers an initial empty project wired up to CI

### CODE REVIEW

**Comment by job13er** [comment]
@mharris717 I hope you don't mind, but it looked like you gave up on https://github.com/mharris717/ember-cli-istanbul and had never published anything in npm, so we decided to go ahead an give it a shot now that our team is starting to work with Ember. I'll probably start working on this in earnest in about 2-4 weeks. Please let me know if you'd like to contribute.

**Comment by sglanzer-fire** [comment]
@jschilli I'm going to be putting some work into this as an alternative to ember-cli-blanket, we think we can get better source map support and istanbul should be more responsive to PRs than blanket is.  You're welcome to join if you're interested.

**Comment by jschilli** [comment]
@sglanzer it's been on my list for a while.

In the meantime, I'm going to update by ember-cli-blanket pr to point @ my fork of blanketjs - if that works for you we can publish an update. -- the update would require ember cli 1.13.x as a minimum

**Comment by sglanzer-fire** [comment]
@jschilli Sounds good, let me know when you're ready to publish

**Pull request merged**
